language: java

jdk:
  - oraclejdk8
  - openjdk8
  - oraclejdk9

addons:
  sonarcloud:
    organization: "maddingo-github"

script:
  - mvn clean org.jacoco:jacoco-maven-plugin:prepare-agent install sonar:sonar
