dist: xenial
language: java

addons:
  sonarcloud:
    organization: "maddingo-github"

matrix:
  include:
    - jdk: openjdk11
      script: scripts/build-jdk11.sh
    - jdk: openjdk8
      script: mvn clean test
