dist: xenial
language: java

cache:
  directories:
    - $HOME/.m2/repository

before_cache:
  - rm -rf $HOME/.m2/no/maddin

addons:
  sonarcloud:
    organization: "maddingo-github"

matrix:
  include:
    - jdk: openjdk11
      script: .travis/build-jdk11.sh
    - jdk: openjdk8
      script: mvn clean test

